# Generated by Django 2.1 on 2018-10-11 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', '----'), ('SP', 'Speaker'), ('AT', 'Attendee'), ('TR', 'Trainer')], max_length=50)),
                ('duration', models.DecimalField(decimal_places=1, help_text='Enter your attendance time in hours eg. 1h', max_digits=5)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('type_of_event', models.CharField(choices=[('', '----'), ('CF', 'Conference'), ('TR', 'Training'), ('WS', 'Workshop'), ('ME', 'Meeting')], max_length=100)),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('end_date', models.DateTimeField(verbose_name='event enddate')),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
