# Generated by Django 2.1 on 2018-10-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
