# Generated by Django 2.1 on 2018-11-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20181023_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('SP', 'Speaker'), ('AT', 'Attendee'), ('TR', 'Trainer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('CF', 'Conference'), ('TR', 'Training'), ('WS', 'Workshop'), ('ME', 'Meeting')], max_length=50),
        ),
    ]
