# Generated by Django 2.1 on 2018-10-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20181019_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='user',
        ),
    ]
