# Generated by Django 2.1 on 2018-11-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20181107_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('SP', 'Speaker'), ('AT', 'Attendee'), ('TR', 'Trainer')], default='SP', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('CF', 'Conference'), ('TR', 'Training'), ('WS', 'Workshop'), ('ME', 'Meeting')], default='CF', max_length=50),
        ),
    ]
