# Generated by Django 2.1 on 2018-11-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20181107_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('SP', 'Speaker'), ('AT', 'Attendee'), ('TR', 'Trainer'), ('OR', 'Organizer')], default='SP', max_length=50),
        ),
    ]
