# Generated by Django 2.1 on 2018-11-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20181107_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
