# Generated by Django 2.1 on 2018-10-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20181022_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('CF', 'Conference'), ('TR', 'Training'), ('WS', 'Workshop'), ('ME', 'Meeting')], max_length=100),
        ),
    ]
