# Generated by Django 2.1 on 2018-10-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20181022_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('', '----'), ('Speaker', 'SP'), ('Attendee', 'AT'), ('Trainer', 'TR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('', '----'), ('CF', 'Conference'), ('TR', 'Training'), ('WS', 'Workshop'), ('ME', 'Meeting')], max_length=100),
        ),
    ]
