# Generated by Django 2.1 on 2018-11-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20181109_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='In dd/mm/yy form', verbose_name='event date'),
        ),
    ]
