# Generated by Django 2.1 on 2018-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_auto_20181109_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='e.g dd/mm/yy', verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='e.g dd/mm/yy', verbose_name='event enddate'),
        ),
    ]
