# Generated by Django 2.1 on 2018-11-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20181120_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.FloatField(),
        ),
    ]
