# Generated by Django 2.1.3 on 2018-11-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_auto_20181129_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
