# Generated by Django 2.1.3 on 2018-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_auto_20181129_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='dd/mm/yy', verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='dd/mm/yy', verbose_name='event enddate'),
        ),
    ]
