# Generated by Django 2.1.3 on 2018-11-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_auto_20181129_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
