# Generated by Django 2.1.3 on 2019-01-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_auto_20181129_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Speaker', 'Speaker'), ('Attendee', 'Attendee')], max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='dd/mm/yy', verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='dd/mm/yy', verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Training', 'Training'), ('Workshop', 'Workshop'), ('Meeting', 'Meeting')], max_length=15, verbose_name='type'),
        ),
    ]
