# Generated by Django 2.1.3 on 2019-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_auto_20190109_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='my_default', max_length=50),
            preserve_default=False,
        ),
    ]
