# Generated by Django 2.1.5 on 2019-01-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_event_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(choices=[('4 hours', '4 hours'), ('8 hours', '8 hours'), ('12 hours', '12 hours'), ('16 hours', '16 hours'), ('20 hours', '20 hours'), ('24 hours', '24 hours')], max_length=50),
        ),
    ]
