# Generated by Django 2.1.5 on 2019-02-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_auto_20190128_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='dd/mm/yy', null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='dd/mm/yy', null=True, verbose_name='end'),
        ),
    ]
