# Generated by Django 2.1 on 2018-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(default=0, help_text='Enter the event type (e.g. conference, training, workshop)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(help_text='Enter either "Speaker" or "Attendee"', max_length=200),
        ),
    ]
