# Generated by Django 2.1 on 2018-08-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20180809_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='activity',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Enter your attendance time in hours', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_participation',
            field=models.CharField(default=0, help_text='Enter either "Speaker" or "Attendee"', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(help_text='Enter the event type (e.g. conference, training, workshop)', max_length=50),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
