# Generated by Django 2.1 on 2018-08-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20180809_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Enter your attendance time in hours', max_digits=5),
        ),
    ]
